expr
    | bitwiseOrExpr

bitwiseOrExpr
    | [bitwiseOrExpr "|"] bitwiseXorExpr

bitwiseXorExpr:
    | [bitwiseXorExpr "$"] bitwiseAndExpr

bitwiseAndExpr
    | [bitwiseAndExpr "&"] shiftExpr

shiftExpr
    | [shiftExpr ("<<" | ">>")] additiveExpr

additiveExpr
    | [additiveExpr ("+" | "-")] multiplicativeExpr

multiplicativeExpr
    | [multiplicativeExpr ("*" | "/" | "%")] castExpr

castExpr
    | castExpr "as" type
    | prefixExpr

prefixExpr
    | prefixOp prefixExpr
    | primaryExpr

prefixOp
    | "+" | "-"
    | "!"

primaryExpr
    | NUMBER
    | CHARACTER
    | primaryKeyword
    | parenExpr

primaryKeyword
    | "true" | "false"

parenExpr
    | "(" expr ")"
